image: Visual Studio 2019

assembly_info:
  patch: false

configuration:
  - Debug
install:
  - set PATH=C:\Ruby25-x64\bin;%PATH%

build_script:
  - pwsh: ./build.ps1 -script build.cake -target Default

test: off
skip_tags: true

deploy:
- provider: GitHub
  auth_token:
    secure: 5g5zfs39hkEhY2AwapE6lVhaeabzuJ/T6MEeK6mLikK+nXOjO57eV4FM6kBxFwCo
  artifact: all
  draft: true
